#!/bin/zsh

# Homebrew
if [ -d /usr/local/Cellar ]; then
  export PATH=/usr/local/bin:/usr/local/sbin:$PATH
fi

export PATH=$HOME/bin:$PATH
export PATH=$PATH:"/usr/local/heroku/bin"
export PATH=$PATH:".local/lib/aws/bin"
