#!/bin/zsh

export RBENV_ROOT=$HOME/.rbenv
# Setup rbenv if it exists
  echo "Setting rbenv"
  eval "$(rbenv init - --no-rehash)"
#export RUBY_CONFIGURE_OPTS="--with-readline-dir=`brew --prefix readline`"
