#!/bin/zsh

platform=`uname`
if [[ "$platform" == 'Linux' ]]; then
  alias ls="ls --color=auto $*"
elif [[ "$platform" == 'Darwin' ]]; then
  alias ls="ls -G $*"
fi

alias la="ls -la $*"

# git alias's
alias gs='git status'
alias gp='git pull'

# Shell tools
alias mytop='top -s1 -o cpu -R -F'

# Ruby
alias be="bundle exec $*"

if [[ -f /usr/local/opt/rbenv/bin/rbenv ]]; then
  alias rb="rbenv $*"
fi

#alias ctags="`brew --prefix`/bin/ctags"

alias global-off='sudo mv /Applications/GlobalProtect{,OFF}.app && pkill -9 -f GlobalProtect'
alias global-on='sudo mv /Applications/GlobalProtect{OFF,}.app'
alias casper-off='sudo mv /usr/sbin/jamfAgent{,-off} && sudo mv /usr/sbin/jamf{,-off} && sudo pkill -9 jamf'
alias casper-on='sudo mv /usr/sbin/jamfAgent{-off,} && sudo mv /usr/sbin/jamf{-off,}'
