#!/bin/zsh

# Setup rbenv if it exists
if [ -d /usr/local/opt/rbenv ]; then
  eval "$(rbenv init - --no-rehash)"
fi
#export RUBY_CONFIGURE_OPTS="--with-readline-dir=`brew --prefix readline`"
export RBENV_ROOT=$HOME/.rbenv
